services:
  - type: web
    name: bagelboy-backend
    env: python
    buildCommand: ./render-build.sh && pip install -r requirements.txt
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT main:app"
    envVars:
      - key: GOOGLE_CREDENTIALS
        value: YOUR_SECRET_JSON_STRING_HERE
      - key: EMAIL_SENDER
        value: your@email.com
      - key: EMAIL_PASSWORD
        value: your-app-password
      - key: EMAIL_RECEIVER
        value: joepheusschen@gmail.com
