
services:
  - type: web
    name: bagelboy-api
    env: python
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: SPREADSHEET_ID
        value: "YOUR_SPREADSHEET_ID"
